import Head from "next/head";
import Navbar from "./Navbar";
import Footer from "./Footer";
import Router from "next/router";
import { useState } from "react";
import Loading from "./Loading";

const Layout = ({ children }) => {
	const [loading, setLoading] = useState(false);

	Router.events.on("routeChangeStart", (url) => {
		setLoading(true);
	});
	Router.events.on("routeChangeComplete", (url) => {
		setLoading(false);
	});
	return (
		<>
			<Head>
				<title>BurgerCrown | India</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link
					rel="icon"
					href="/images/logo/logo.png"
					sizes="16x16"
					type="image/png"
				/>
			</Head>
			<Navbar />
			{loading ? <Loading /> : children}
			<Footer />
		</>
	);
};
export default Layout;
