import Head from "next/head";
import Navbar from "./Navbar";
import Footer from "./Footer";
const Layout = ({ children }) => {
	return (
		<>
			<Head>
				<title>BurgerCrown | India</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link
					rel="icon"
					href="/images/logo/logo.png"
					sizes="16x16"
					type="image/png"
				/>
			</Head>
			<Navbar />
			{children}
			<Footer />
		</>
	);
};
export default Layout;
