import Head from "next/head";
import Image from "next/image";
import Slider from "../components/Slider";
import OurMenu from "../components/OurMenu";
import Deals from "../components/Deals";
import Special from "../components/Special";
import { useEffect } from "react";
import axios from "axios";
export default function Home() {
  useEffect(() => {
    const dbConnect = async () => {
      await axios.get("https://burger-crown.vercel.app/api/products");
    };
    dbConnect();
  }, []);

  return (
    <>
      <Head>
        <title>BurgerCrown | India</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/images/logo/logo.png"
          sizes="16x16"
          type="image/png"
        />
      </Head>
      <Slider />
      <OurMenu />
      <Deals />
      <Special />
    </>
  );
}
